# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md
indent_style = "Block"

# issue 3343
# inline_attribute_width = 80

max_width = 80
tab_spaces = 4

binop_separator = "Back"

where_single_line = true
format_strings = true

match_block_trailing_comma = true
force_multiline_blocks = true

normalize_comments = true
wrap_comments = true

use_field_init_shorthand = true

reorder_imports = false
reorder_modules = false
